http:
  public:
    schema: "http"
    domain: "make-it-public.com"
    port: 8080
  listen: ":8080"
  conn_limit: 32
reverse_proxy:
  listen: ":8081"
api:
  listen: ":8082"
  scheme: "http"

auth:
  redis_addr: "localhost:6379"
  redis_password: ""
  key_prefix: "MIT::AUTH::"
  salt: "someRandomSalt"

